steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        make setup
    - name: Check Black
      run: |
        black --check
    - name: Pytest
      run: |
        make test
